apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-grade-app
  labels:
    app: student-grade-app
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: student-grade-app

  template:
    metadata:
      labels:
        app: student-grade-app

    spec:
      containers:
        - name: student-grade-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP